### ISSUE TITLE
Generating the proper audio files

### ISSUE THREAD

**Issue by jurecotic** [JohannesMTC/ESP32_MAS#1]
Hello Johannes,

I'm having trouble converting my audio files to the right format. How did you convert them? Using Sox or ffmpeg?

**Comment by JohannesMTC** [comment]
I use Audacity.
A free audio software.
Set the sample rate to 22050.
Then adapt the final tracks to the project.
Everything as RAW audio export.
Set export 8 bit signed.
The file extension should then be aiff.
The files need no rework and can be loaded in the spiffs.

For sox the following command should bring the desired result.

> sox INFILE.wav -b 8 -s -c 1 -r 22050 -t raw OUTFILE.aiff

I do not even try it myself though.

**Comment by JasXSL** [comment]
You might want to put this in the readme. I generated AIFF files from adobe audition with the same specs and they generated popping noises on loop. After exporting them through audacity, it worked fine.
