### ISSUE TITLE
volume

### ISSUE THREAD

**Issue by DaveSchwarzwald** [JohannesMTC/ESP32_MAS#3]
i tried to change the volume by the .setVolume() or setGain() function, but the sound is always the same. If as NoDAC configured and with 1-T Output as from earlephilhower described, this functions do anything? what is the rigth setting for the pitch to get original speed? 0.0?

**Comment by JohannesMTC** [comment]
Sorry for reporting so late.

**That sounds like an overload of your transistor?**

Set the ".setVolume ()" function very low! Values between 8 and 32 should fit?
Then please use the settings of the ".GetGain ()" function to get a satisfactory result!
The "setPitch ()" function supports _float_ values from 1 to 4.
0 = normal speed
1 = twice the speed
3 = fourfold speed
I hope this helps?
